### ISSUE TITLE
Runtime errors

### ISSUE THREAD

**Issue by fdrobnic** [International-Data-Spaces-Association/IDS-VocabularyProvider#11]
Hello, I'm trying to run the vocabulary provider using docker-compose and try to configure it to use a github repo. All other URLs point to localhost. Saving configuration doesn't succeed and displays the following in the log (credentials omitted):

> vocol@0.0.1 start /home/project/vocol
> node ./bin/www "8888" "3030" "http://vocab-fuseki"

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
http://vocab-fuseki:3030/connectorData/sparql
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(node:18) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
VoCol server is running on port 8888
Jena Fuseki server is running on port 3030
GET / 200 7.677 ms - 22798
/home/project
Cloning into 'repoFolder'...
fatal: repository 'https://<user>:<passw>@github.com/' not found
cd: no such file or directory: repoFolder
cd: no such file or directory: ../vocol/
/home/project
POST /config 200 843.076 ms - 1495
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.css 200 6.502 ms - 146010
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap.min.css 200 5.711 ms - 121200
GET /javascripts/bower_components/bootstrap/dist/css/bootstrap-theme.min.css 200 13.361 ms - 23409
GET /stylesheets/style.css 200 28.442 ms - 2986
GET /javascripts/bower_components/jquery/dist/jquery.min.js 200 16.754 ms - 86659
GET /javascripts/bower_components/bootstrap/dist/js/bootstrap.min.js 200 30.106 ms - 37045
/home/project/vocol/routes/config.js:74
                          throw err;
                          ^

[Error: ENOENT: no such file or directory, open 'jsonDataFiles/userConfigurations.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'jsonDataFiles/userConfigurations.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vocol@0.0.1 start: `node ./bin/www "8888" "3030" "http://vocab-fuseki"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vocol@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by waleedshabbir1** [comment]
It's saying repository not found 
Is it a private repository?

**Comment by fdrobnic** [comment]
Yes, and I have chosen the "private" option in the config.

**Comment by waleedshabbir1** [comment]
yes, I was able to reproduce this issue with the private repository. 
I will try to fix it in the upcoming days

**Comment by waleedshabbir1** [comment]
I tried again by generating a new GitHub personal access token. 
It is working fine for the private repository 

You have to provide your username and personal access token when linking Vocabulary Provider to the Github repo, and you have to make sure that you have allowed read/write permission when creating a personal access token

**Comment by fdrobnic** [comment]
Thank you, will try later.

**Comment by fdrobnic** [comment]
I have just tried to save a configuration using the Personal Access Token with the admin rights (Full control of projects). The error log is completely the same as in the original post.

**Comment by waleedshabbir1** [comment]
In the error, it is stating repository not found 
Are you pasting the clone link in the configuration and giving the correct owner and repository name? 
Is it possible to share the URL of the repository even if it's private?

I tried with my own personal repository and my own personal access token and it is working fine.
