### ISSUE TITLE
Fix pom

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-VocabularyProvider#2]
Pom links to non-existing maven repository

https://github.com/International-Data-Spaces-Association/IDS-VocabularyProvider/blob/047d5e0a0169b24fe849bf48a14b4f1e1dfaa11a/eis-vocab/pom.xml#L101

**Comment by janniswarnat** [comment]
I ran into the same problem. Works when changing to `https`.

**Comment by lcomet** [comment]
> I ran into the same problem. Works when changing to `https`.

In my case, this also solves the issue.
