### ISSUE TITLE
Missing repository

### ISSUE THREAD

**Issue by fdrobnic** [International-Data-Spaces-Association/IDS-VocabularyProvider#8]
The buiding scripts and docker-compose file refer to some images in the Docker Hub repository named idsvocabularyprovider which is nonexistent.

**Comment by waleedshabbir1** [comment]
@fdrobnic you have to first build Images. 
You have to run this script 
[buildImagesLocally](https://github.com/International-Data-Spaces-Association/IDS-VocabularyProvider/blob/main/docker/buildImagesLocally.sh)

The instructions are already available in the README
